packages:
  - app
  - lib/*
  - mcp
  - embed

allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - '@cloudflare/workers-types*'
  - svelte-check*
  - miniflare*
  - wrangler*
  - vite-plugin-mog*
  - workerd*
  - '@cloudflare/workerd-*'

onlyBuiltDependencies:
  - deadlock_api_client
  - esbuild
  - msw
  - sharp
  - workerd
