name: Setup Pipeline
description: Setup Nix environment and install dependencies

inputs:
  github-token:
    description: GitHub token for Nix installation
    required: true

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ inputs.github-token }}

    - name: Setup Cachix
      uses: cachix/cachix-action@v16
      with:
        name: deadlog

    - name: Setup Nix dev environment
      uses: nicknovitski/nix-develop@v1

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
