[package]
name = "deadlog"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
default = ["serve"]
serve = ["deadlog-site/serve"]

[dependencies]
anyhow.workspace = true
clap.workspace = true
deadlog-site.workspace = true
deadlog-meta = { path = "../meta" }
deadlog-scraper = { path = "../scraper" }
deadlog-stats = { path = "../stats" }
