export {
	queryChangelogs,
	getAllChangelogs,
	getAllChangelogSlugs,
	getChangelogsCount,
	getChangelogBySlug,
	getUpdatesForChangelogs,
	getAllHeroes,
	getAllItems,
	getHeroBySlug,
	getReleasedHeroSlugs,
	getItemBySlug,
	getReleasedItemSlugs,
	getHeroAbilities,
	type HeroAbility,
	getChangelogAbilityIcons,
	type ChangelogAbilityIcon,
	getChangelogsByHeroId,
	getChangelogsByItemId,
	getMainChangelogIdSequence,
	getHeroLastModified,
	getItemLastModified,
	getChangelogIcons,
	type ScrapedChangelog,
	type EntityChangelog,
	type ScrapedItem,
	type EnrichedHero,
	type EnrichedItem
} from './queries';

export type { EntityType, EntityIcon, ChangelogEntityIcon } from './types/deadlockApi';
