import { canonicalOriginRedirect } from './src/lib/server/canonical-origin';
import { adapterWillStore, isEdgeCacheable } from './src/lib/server/cache-policy';
// Generated by adapter-cloudflare before Wrangler bundles this entrypoint.
// @ts-expect-error The generated module does not exist until the production build runs.
import generatedWorker from './.svelte-kit/cloudflare/_worker.js';

interface Env {
	ASSETS: Fetcher;
	DB: D1Database;
	PUBLIC_COUNTERSCALE_REPORTER_URL: string;
	PUBLIC_COUNTERSCALE_SITE_ID: string;
}

// includeSubDomains and preload are deliberately omitted: they commit every current and
// future subdomain to HTTPS for a year, which is a separate decision from securing
// deadlog.io itself.
const STRICT_TRANSPORT_SECURITY = 'max-age=31536000';

const svelteKitWorker = generatedWorker as {
	fetch(request: Request, env: Env, context: ExecutionContext): Promise<Response>;
};

const PINNED_MARKER = 'x-deadlog-pinned';

// Pin D1-backed 404s and 308s excluded by the adapter's cache status allowlist.
function pinAdapterCacheGaps(
	request: Request,
	response: Response,
	context: ExecutionContext
): void {
	if (request.method !== 'GET') return;
	if (response.headers.has(PINNED_MARKER)) return;
	if (adapterWillStore(response) || !isEdgeCacheable(response)) return;
	const pinned = new Response(response.clone().body, response);
	pinned.headers.set(PINNED_MARKER, '1');
	context.waitUntil(caches.default.put(request, pinned));
}

export default {
	async fetch(request, env, context) {
		let response = canonicalOriginRedirect(request);
		if (!response) {
			response = await svelteKitWorker.fetch(request, env, context);
			pinAdapterCacheGaps(request, response, context);
		}

		// Only responses served over TLS carry HSTS; user agents ignore it otherwise, and
		// the canonical-origin redirect already upgrades plain-HTTP requests. The redirect
		// is deliberately inside this branch: the https www -> apex 308 is the only
		// response that ever pins a policy on www.deadlog.io.
		if (!request.url.startsWith('https:')) return response;

		const secured = new Response(response.body, response);
		secured.headers.set('Strict-Transport-Security', STRICT_TRANSPORT_SECURITY);
		secured.headers.delete(PINNED_MARKER);
		return secured;
	}
} satisfies ExportedHandler<Env>;
