import { canonicalOriginRedirect } from './src/lib/server/canonical-origin';
// Generated by adapter-cloudflare before Wrangler bundles this entrypoint.
// @ts-expect-error The generated module does not exist until the production build runs.
import generatedWorker from './.svelte-kit/cloudflare/_worker.js';

interface Env {
	ASSETS: Fetcher;
	DB: D1Database;
	PUBLIC_COUNTERSCALE_REPORTER_URL: string;
	PUBLIC_COUNTERSCALE_SITE_ID: string;
}

const svelteKitWorker = generatedWorker as {
	fetch(request: Request, env: Env, context: ExecutionContext): Promise<Response>;
};

export default {
	async fetch(request, env, context) {
		const redirect = canonicalOriginRedirect(request);
		if (redirect) return redirect;

		return svelteKitWorker.fetch(request, env, context);
	}
} satisfies ExportedHandler<Env>;
