import { canonicalOriginRedirect } from './src/lib/server/canonical-origin';
// Generated by adapter-cloudflare before Wrangler bundles this entrypoint.
// @ts-expect-error The generated module does not exist until the production build runs.
import generatedWorker from './.svelte-kit/cloudflare/_worker.js';

interface Env {
	ASSETS: Fetcher;
	DB: D1Database;
	PUBLIC_COUNTERSCALE_REPORTER_URL: string;
	PUBLIC_COUNTERSCALE_SITE_ID: string;
}

// includeSubDomains and preload are deliberately omitted: they commit every current and
// future subdomain to HTTPS for a year, which is a separate decision from securing
// deadlog.io itself.
const STRICT_TRANSPORT_SECURITY = 'max-age=31536000';

const svelteKitWorker = generatedWorker as {
	fetch(request: Request, env: Env, context: ExecutionContext): Promise<Response>;
};

export default {
	async fetch(request, env, context) {
		const response =
			canonicalOriginRedirect(request) ??
			(await svelteKitWorker.fetch(request, env, context));

		// Only responses served over TLS carry HSTS; user agents ignore it otherwise, and
		// the canonical-origin redirect already upgrades plain-HTTP requests. The redirect
		// is deliberately inside this branch: the https www -> apex 308 is the only
		// response that ever pins a policy on www.deadlog.io.
		if (new URL(request.url).protocol !== 'https:') return response;

		const secured = new Response(response.body, response);
		secured.headers.set('Strict-Transport-Security', STRICT_TRANSPORT_SECURITY);
		return secured;
	}
} satisfies ExportedHandler<Env>;
